export const CARTGET_REQUEST = "CARTGET_REQUEST"
export const CARTGET_SUCCESS = "CARTGET_SUCCESS"
export const CARTGET_FAILURE = "CARTGET_FAILURE"


export const DELETE_DATA="DELETE_DATA"
export const ADDTOCART="ADDTOCART"
export const UPDATE_CART="UPDATE_CART"