export const PRODUCTGET_REQUEST = "PRODUCTGET_REQUEST"
export const PRODUCTGET_SUCCESS = "PRODUCTGET_SUCCESS"
export const PRODUCTGET_FAILURE = "PRODUCTGET_FAILURE"


export const DELETE_PRODUCT="DELETE_PRODUCT"
export const ADDTOPRODUCT="ADDTOPRODUCT"
export const UPDATE_PRODUCT="UPDATE_PRODUCT"