export const ADDRESSGET_REQUEST = "ADDRESSGET_REQUEST"
export const ADDRESSGET_SUCCESS = "ADDRESSGET_SUCCESS"
export const ADDRESSGET_FAILURE = "ADDRESSGET_FAILURE"


export const DELETE_ADDRESS="DELETE_ADDRESS"
export const ADD_ADDRESS="ADD_ADDRESS"
export const UPDATE_ADDRESS="UPDATE_ADDRESS"